### ISSUE TITLE
How does the script behave if it finds two files with the same name?

### ISSUE THREAD

**Issue by cmedinag** [mb243/exifsort#1]
Hello:

I've been overviewing the code, and did not realize anywhere how would the script behave if it tries to move a file to a folder where another file with the same name already exists.
I assume it would overwrite it, but just wanted to be sure.

If this is the case, what would I need to modify in order to add a suffix or so to the second file?

Thanks in advance!

**Comment by mb243** [comment]
If there is a file in the destination folder with the same name, it will be overwritten. There's not currently any mechanism for detecting this situation and preventing collisions. It's not ideal, but this script should ideally be run with a clean environment. The upside is that this prevents duplicate files if the script is aborted and later re-run.

**Comment by mb243** [comment]
I just realized I didn't answer your question:

> If this is the case, what would I need to modify in order to add a suffix or so to the second file?

The simplest way to do this would be to add the `-b` tag to mv, which would create a backup.
