### ISSUE TITLE
Does not work under DSM 6.0.2-8451 Update 1

### ISSUE THREAD

**Issue by cmedinag** [mb243/exifsort#2]
It seems imagemagick is missing, because it cannot run the identify command.

**Comment by mb243** [comment]
It looks like ImageMagick's identify tool has been removed either partially or completely from DSM:

> ash-4.3# find / -name *identify*
Returns nothing

In any case, this isn't a fault of the script, but rather of a recent change that Synology made. It's outside of my ability to resolve unless that command is somehow made available again within DSM.
